updating useAsyncStorage syntax
reason-react-native/async-storage pull request #4
Opened 2020-11-22 16:58 UTC by idkjs

Lets user do:

#### `ReactNativeAsyncStorage.asyncStorageState`

```reason
type asyncStorageState = {
  getItem: unit => Js.Promise.t(Js.Null.t(string)),
  setItem: string => Js.Promise.t(unit),
  mergeItem: string => Js.Promise.t(unit),
  removeItem: unit => Js.Promise.t(unit),
};

let key = "@@Key"
 let ReactNativeAsyncStorage.{getItem, setItem} =
    ReactNativeAsyncStorage.useAsyncStorage("@@Key");
```

Instead of 

```reason
 let useAsyncStorage=
    ReactNativeAsyncStorage.useAsyncStorage("@@Key");

let getItem =useAsyncStorage##getItem;
```

See updated [README.md](https://github.com/reason-react-native/async-storage/blob/1678c86/README.md#L49)

2020-11-24 17:14 UTC, tatchi requested changes

2020-11-24 17:14 UTC, tatchi commented on README.md
> +  let getItem = () => useAsyncStorage##getItem();
Cannot this line be removed?

2020-12-03 11:29 UTC, idkjs commented on README.md
> +  let getItem = () => useAsyncStorage##getItem();
Yes. Done. Thank you.

2020-12-08 18:35 UTC, tatchi approved these changes

2021-01-08 10:48 UTC, MoOx requested changes
Thanks for this PR! Could the example be more straight forward without styles for example? To avoid unecessary noise so the developer can focus on the actual interesting code, thanks!

2021-01-11 11:40 UTC, idkjs commented
@MoOx https://github.com/reason-react-native/async-storage/pull/4#pullrequestreview-564167837 done

2021-02-19 13:56 UTC, MoOx commented
I removed example as they were way to complex to quickly illustrate how to use the hook. If you want to another PR, but without UI & faker & unecessary stuff for the developer to understand the core of the usage.

2021-02-19 13:56 UTC, merged

2021-02-19 14:05 UTC, MoOx commented
I rolled back the change and added record syntax as `useAsyncStorage_` with a deprecation notice for old syntax.